# Generated by scripts/generate_shim_stubs.py -- do not edit by hand.
#
# The names below are read from the imported module, which fills itself from the
# compiled extension at import time. Regenerate after any change to the bindings,
# and tests/python/test_shim_stubs.py fails if this file and the live module disagree.
#
# Every type is Any because the extension publishes no signatures to Python; a more
# specific claim here would be unverifiable, which is worse than an honest Any.

from typing import Any

CovarianceEstimate: Any
CvarRequest: Any
CvarSolution: Any
INFEASIBLE: Any
LinearProgramResult: Any
LinearSolve: Any
LpStatus: Any
NUMERICAL_FAILURE: Any
OPTIMAL: Any
OptimizationRequest: Any
OptimizerInputs: Any
PortfolioOptimizer: Any
PortfolioSolution: Any
RiskParitySolution: Any
UNBOUNDED: Any
condition_number: Any
efficient_frontier: Any
eigenvalues: Any
ewma_covariance: Any
maximum_sharpe: Any
minimise_cvar: Any
minimum_variance: Any
risk_parity: Any
sample_covariance: Any
shrinkage_covariance: Any
solve: Any
solve_linear_program: Any
