# Generated by scripts/generate_shim_stubs.py -- do not edit by hand.
#
# The names below are read from the imported module, which fills itself from the
# compiled extension at import time. Regenerate after any change to the bindings,
# and tests/python/test_shim_stubs.py fails if this file and the live module disagree.
#
# Every type is Any because the extension publishes no signatures to Python; a more
# specific claim here would be unverifiable, which is worse than an honest Any.

from typing import Any

AMERICAN: Any
ARITHMETIC: Any
AsianOption: Any
AverageType: Any
BarrierOption: Any
BarrierType: Any
BinomialResult: Any
BlackScholes: Any
BumpPolicy: Any
CALL: Any
DOWN_AND_OUT: Any
EUROPEAN: Any
EuropeanOption: Any
ExerciseStyle: Any
GEOMETRIC: Any
Greeks: Any
MarketParams: Any
MixedFifthDerivatives: Any
MixedFourthDerivatives: Any
MixedThirdDerivatives: Any
OptionType: Any
PUT: Any
PricingResult: Any
SpotDerivatives: Any
UP_AND_OUT: Any
VolCrossDerivatives: Any
barrier_continuity_constant: Any
black_scholes: Any
black_scholes_greeks: Any
black_scholes_mixed_fifth_derivatives: Any
black_scholes_mixed_fourth_derivatives: Any
black_scholes_mixed_third_derivatives: Any
black_scholes_spot_derivatives: Any
black_scholes_vol_cross_derivatives: Any
continuity_corrected_barrier: Any
crr_binomial: Any
crr_convergence_to_black_scholes: Any
finite_difference_greeks: Any
geometric_asian_price: Any
put_call_parity_residual: Any
