# Generated by scripts/generate_shim_stubs.py -- do not edit by hand.
#
# The names below are read from the imported module, which fills itself from the
# compiled extension at import time. Regenerate after any change to the bindings,
# and tests/python/test_shim_stubs.py fails if this file and the live module disagree.
#
# Every type is Any because the extension publishes no signatures to Python; a more
# specific claim here would be unverifiable, which is worse than an honest Any.

from typing import Any

BacktestReport: Any
BootstrapEstimate: Any
BootstrapKind: Any
CoverageTestResult: Any
IID: Any
MOVING_BLOCK: Any
RiskEngine: Any
RiskEstimate: Any
TransitionCounts: Any
ViolationSeries: Any
backtest_var: Any
bootstrap_es: Any
bootstrap_var: Any
christoffersen_conditional_coverage_test: Any
christoffersen_independence_test: Any
flag_violations: Any
gaussian_es: Any
gaussian_var: Any
historical_es: Any
historical_var: Any
kupiec_pof_test: Any
linear_pnl: Any
monte_carlo_es: Any
monte_carlo_var: Any
returns: Any
sample_covariance: Any
suggested_block_length: Any
transition_counts: Any
