# Generated by scripts/generate_shim_stubs.py -- do not edit by hand.
#
# The names below are read from the imported module, which fills itself from the
# compiled extension at import time. Regenerate after any change to the bindings,
# and tests/python/test_shim_stubs.py fails if this file and the live module disagree.
#
# Every type is Any because the extension publishes no signatures to Python; a more
# specific claim here would be unverifiable, which is worse than an honest Any.

from typing import Any

autocorrelation: Any
mean: Any
mean_of_largest_sorted: Any
quantile: Any
sample_stddev: Any
sample_variance: Any
standard_error_of_mean: Any
sum_compensated: Any
