# Generated by scripts/generate_shim_stubs.py -- do not edit by hand.
#
# The names below are read from the imported module, which fills itself from the
# compiled extension at import time. Regenerate after any change to the bindings,
# and tests/python/test_shim_stubs.py fails if this file and the live module disagree.
#
# Every type is Any because the extension publishes no signatures to Python; a more
# specific claim here would be unverifiable, which is worse than an honest Any.

from typing import Any

HestonParams: Any
HestonPriceResult: Any
HestonSimulation: Any
antithetic_paths_matrix: Any
antithetic_terminal_prices: Any
expected_log_return: Any
heston_step_refinement_gap: Any
paths_matrix: Any
price_heston_european: Any
simulate_heston: Any
terminal_prices: Any
terminal_prices_physical: Any
