# Generated by scripts/generate_shim_stubs.py -- do not edit by hand.
#
# The names below are read from the imported module, which fills itself from the
# compiled extension at import time. Regenerate after any change to the bindings,
# and tests/python/test_shim_stubs.py fails if this file and the live module disagree.
#
# Every type is Any because the extension publishes no signatures to Python; a more
# specific claim here would be unverifiable, which is worse than an honest Any.

from typing import Any

DistributionShift: Any
ExposureVector: Any
FactorClass: Any
FactorContribution: Any
FactorSet: Any
FactorSummary: Any
Portfolio: Any
Position: Any
PositionContribution: Any
RiskFactor: Any
Scenario: Any
ScenarioEngine: Any
ScenarioKind: Any
ScenarioResult: Any
ScenarioSample: Any
ScenarioSetResult: Any
Shock: Any
credit_spread: Any
deterministic: Any
equity_index: Any
historical: Any
monte_carlo: Any
rate: Any
run_historical_scenarios: Any
run_monte_carlo_scenarios: Any
run_scenario: Any
sample_factor_moves: Any
shift_covariance: Any
volatility: Any
