#!/usr/bin/env python3
"""Generate the type stubs for the eight Python faces of the C++ submodules.

    uv run python scripts/generate_shim_stubs.py

`python/quantrisk/stress.py` and its seven siblings populate themselves at import time with
`copy_core_names()`, because pybind11 binds `_quantrisk.stress` as an *attribute* of the
extension rather than as a submodule in `sys.modules`. That is what makes
`from quantrisk.stress import FactorSet` work at run time, and it is also why every static
tool fails on it: nothing in the source text names `FactorSet`, so mypy reports
`Module has no attribute` and an editor offers no completion. Both are wrong about code that
runs fine, which is the definition of a false positive worth eliminating.

The fix is a `.pyi` beside each shim, and the names in it are read from the **imported
module**, never typed by hand. That matters twice over: a hand-written list is 159 chances to
transcribe something incorrectly, and a generated one cannot disagree with the binding it was
generated from. `tests/python/test_shim_stubs.py` regenerates the text and compares, so
adding a name to the C++ module without regenerating the stub fails CI rather than silently
degrading the typing.

Every declaration is `Any`, and that is deliberate rather than lazy. The extension exports no
signatures to Python at all — a `.pyi` claiming `def price(self, paths: int) -> float` would
be a claim about C++ that nothing checks. Declaring the *name* with an unknown type is exactly
what is known: the attribute exists, and its signature lives in `cpp/include`.
"""

from __future__ import annotations

import importlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "python"))

SHIM_MODULES = (
    "stats",
    "special",
    "pricing",
    "stochastic",
    "monte_carlo",
    "risk",
    "portfolio",
    "stress",
)

HEADER = (
    "# Generated by scripts/generate_shim_stubs.py -- do not edit by hand.\n"
    "#\n"
    "# The names below are read from the imported module, which fills itself from the\n"
    "# compiled extension at import time. Regenerate after any change to the bindings,\n"
    "# and tests/python/test_shim_stubs.py fails if this file and the live module disagree.\n"
    "#\n"
    "# Every type is Any because the extension publishes no signatures to Python; a more\n"
    "# specific claim here would be unverifiable, which is worse than an honest Any.\n"
)


def stub_text(module_name: str) -> str:
    """The stub body for one shim module, derived from what it actually exports."""
    module = importlib.import_module(f"quantrisk.{module_name}")
    # __all__ is the authoritative export list; dir() would also report the
    # `annotations` future-import and anything a facade happened to import for its own use.
    declared = getattr(module, "__all__", None)
    if declared is None:
        names = sorted(name for name in dir(module) if not name.startswith("_"))
    else:
        names = sorted(set(declared))
        missing = [name for name in names if not hasattr(module, name)]
        if missing:
            raise SystemExit(f"quantrisk.{module_name}.__all__ names {missing} which do not exist")
    lines = [HEADER, "from typing import Any", ""]
    lines += [f"{name}: Any" for name in names]
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    written = 0
    for module_name in SHIM_MODULES:
        target = ROOT / "python" / "quantrisk" / f"{module_name}.pyi"
        text = stub_text(module_name)
        if not target.exists() or target.read_text(encoding="utf-8") != text:
            target.write_text(text, encoding="utf-8")
            written += 1
        name_count = sum(1 for line in text.splitlines() if line.endswith(": Any"))
        print(f"  {module_name:12s} {name_count:3d} names")
    print(f"wrote {written} stub file(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
